
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  scraper
  
Globals:
  Function:
    Timeout: 60

Resources:
  FundraiserNodeModulesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: node_modules
      Description: Node modules layer
      ContentUri: ./build/layers/lambdas_example_npm_packages/nodejs
      CompatibleRuntimes:
        - nodejs14.x
      LicenseInfo: 'MIT'
      RetentionPolicy: Retain
  FundraiserGeneralLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: fundraiser_general_layer
      Description: General functions
      ContentUri: build/layers
      CompatibleRuntimes:
        - nodejs14.x
      LicenseInfo: 'MIT'
      RetentionPolicy: Retain
  ScrapeApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      Cors:
        AllowMethods: "'OPTIONS,GET,POST,PUT,PATCH,DELETE'"
        AllowHeaders: "'Content-Type,Set-Cookie,Authorization,X-Amz-Date,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"
  ScrapeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/lambdas/lambda_scrape_account_info
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      MemorySize: 512
      Timeout: 30
      Events:
        GetInfo:
          Type: Api
          Properties:
            Path: /scrape
            Method: get
            RestApiId: !Ref ScrapeApi
      Layers:
        - !Ref FundraiserNodeModulesLayer
        - !Ref FundraiserGeneralLayer
      Environment:
        Variables:
          REGION: eu-central-1